server:
  port: 1453

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reactive-database
      username: blacksea
      password: blacksea
      authentication-database: admin